# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserOps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='UserOps.Role'),
        ),
    ]
