# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserOps', '0002_auto_20180809_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='menu1',
            field=models.CharField(blank=True, help_text='\u9876\u7ea7\u83dc\u5355\u6709\u4e2adata-menu \u5c5e\u6027\uff0c\u4ee5\u53ca\u83dc\u5355\u8981\u5199\u4ed6', max_length=32, verbose_name='\u4e00\u7ea7\u83dc\u5355\u7684\u5c5e\u6027'),
        ),
    ]
