# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserOps', '0003_auto_20180809_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menus',
            options={'verbose_name': 'Menus', 'verbose_name_plural': 'Menus'},
        ),
    ]
