# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserOps', '0004_auto_20180814_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='menu1',
        ),
        migrations.AddField(
            model_name='menus',
            name='parent_copy',
            field=models.IntegerField(blank=True, help_text='\u9876\u7ea7\u83dc\u5355\u8bbe\u7f6e\u4e3a-1,\u4e3a\u4e86treetable', null=True, verbose_name='\u7236\u7ea7\u83dc\u5355\u62f7\u8d1d'),
        ),
    ]
