# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sql_audit_order',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sql_audit_order',
            name='order_db',
        ),
        migrations.RemoveField(
            model_name='sql_order_execute_result',
            name='order',
        ),
        migrations.AlterModelTable(
            name='order_system',
            table='order_system',
        ),
        migrations.AlterModelTable(
            name='project_order',
            table='project_order',
        ),
        migrations.DeleteModel(
            name='SQL_Audit_Order',
        ),
        migrations.DeleteModel(
            name='SQL_Order_Execute_Result',
        ),
    ]
