# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpsControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log_ansible_playbook',
            table='log_ansible_playbook',
        ),
    ]
