# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpsControl', '0002_auto_20181112_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ansible_playbook_number',
            old_name='playbook_server',
            new_name='playbook_host',
        ),
        migrations.RenameField(
            model_name='log_ansible_playbook',
            old_name='ans_server',
            new_name='ans_host',
        ),
        migrations.RemoveField(
            model_name='ansible_script',
            name='script_service',
        ),
        migrations.AddField(
            model_name='ansible_script',
            name='auth_prod',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=b'\xe6\x8e\x88\xe6\x9d\x83\xe4\xba\xa7\xe5\x93\x81\xe7\xba\xbf'),
        ),
        migrations.AlterField(
            model_name='ansible_inventory_groups_server',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_group_host', to='OpsControl.Ansible_Inventory_Groups'),
        ),
        migrations.AlterField(
            model_name='ansible_playbook',
            name='playbook_server_model',
            field=models.CharField(blank=True, choices=[(b'prod_line', 'prod_line'), (b'group', 'group'), (b'custom', 'custom')], max_length=10, null=True, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe9\x80\x89\xe6\x8b\xa9\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterModelTable(
            name='ansible_inventory',
            table='ansible_inventory',
        ),
        migrations.AlterModelTable(
            name='ansible_inventory_groups',
            table='ansible_inventory_groups',
        ),
        migrations.AlterModelTable(
            name='ansible_inventory_groups_server',
            table='ansible_inventory_groups_host',
        ),
        migrations.AlterModelTable(
            name='ansible_playbook',
            table='ansible_playbook',
        ),
        migrations.AlterModelTable(
            name='ansible_playbook_number',
            table='ansible_playbook_number',
        ),
        migrations.AlterModelTable(
            name='ansible_script',
            table='ansible_script',
        ),
        migrations.AlterModelTable(
            name='log_ansible_model',
            table='log_ansible_model',
        ),
    ]
