# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeOps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log_project_config',
            table='log_project_config',
        ),
        migrations.AlterModelTable(
            name='project_assets',
            table='project_assets',
        ),
        migrations.AlterModelTable(
            name='project_config',
            table='project_config',
        ),
        migrations.AlterModelTable(
            name='project_number',
            table='project_number',
        ),
        migrations.AlterModelTable(
            name='service_assets',
            table='service_assets',
        ),
    ]
