# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u83dc\u5355\u540d')),
                ('parent_copy', models.IntegerField(blank=True, help_text='\u9876\u7ea7\u83dc\u5355\u8bbe\u7f6e\u4e3a-1,\u4e3a\u4e86treetable', null=True, verbose_name='\u7236\u7ea7\u83dc\u5355\u62f7\u8d1d')),
                ('show', models.BooleanField(default=False, help_text='\u83dc\u5355\u662f\u5426\u663e\u793a\uff0c\u9ed8\u8ba4\u4e0d\u663e\u793a', verbose_name='\u662f\u5426\u663e\u793a')),
                ('spread', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5c55\u5f00')),
                ('href', models.CharField(blank=True, default='javascript:void(0)', help_text='\u7ed9\u83dc\u5355\u8bbe\u7f6e\u4e00\u4e2aurl\u5730\u5740', max_length=300, null=True, verbose_name='\u83dc\u5355\u5730\u5740')),
                ('priority', models.IntegerField(blank=True, help_text='\u83dc\u5355\u7684\u663e\u793a\u987a\u5e8f,\u4f18\u5148\u7ea7\u8d8a\u5927\u663e\u793a\u8d8a\u9760\u524d', null=True, verbose_name='\u663e\u793a\u4f18\u5148\u7ea7')),
                ('target', models.CharField(blank=True, help_text='\u5982\u679c\u662f\u65b0\u6253\u5f00\u5219\u586b\u5199,__blank', max_length=32, null=True, verbose_name='\u6253\u5f00\u65b9\u5f0f')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u56fe\u6807\u4ee3\u7801')),
                ('parent', models.ForeignKey(blank=True, default=0, help_text='\u5982\u679c\u6dfb\u52a0\u7684\u662f\u5b50\u83dc\u5355\uff0c\u8bf7\u9009\u62e9\u7236\u83dc\u5355', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Menus', verbose_name='\u7236\u7ea7\u83dc\u5355')),
            ],
            options={
                'verbose_name': 'Menus',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('menus', models.ManyToManyField(to='system.Menus')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('roles', models.ManyToManyField(blank=True, to='system.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
