# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menus',
            table='Menus',
        ),
    ]
