# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-29 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20180817_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='LarryMenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u83dc\u5355\u540d')),
                ('font', models.CharField(default='larry-icon', max_length=32, verbose_name='\u5b57\u4f53')),
                ('icon', models.CharField(default='larry-widgets', max_length=32, verbose_name='\u56fe\u6807')),
                ('url', models.CharField(blank=True, default='javascript:void(0)', help_text='\u7ed9\u83dc\u5355\u8bbe\u7f6e\u4e00\u4e2aurl\u5730\u5740', max_length=300, null=True, verbose_name='\u83dc\u5355\u5730\u5740')),
                ('param', models.CharField(blank=True, default='', help_text='\u7ed9\u83dc\u5355\u8bbe\u7f6e\u53c2\u6570', max_length=300, null=True, verbose_name='\u53c2\u6570')),
                ('condition', models.CharField(blank=True, default='', help_text='\u8bbe\u5b9a\u4e00\u4e2a\u72b6\u6001', max_length=300, null=True, verbose_name='\u72b6\u6001')),
                ('spread', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5c55\u5f00')),
                ('pid', models.ForeignKey(blank=True, default=0, help_text='\u5982\u679c\u6dfb\u52a0\u7684\u662f\u5b50\u83dc\u5355\uff0c\u8bf7\u9009\u62e9\u7236\u83dc\u5355', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.LarryMenus', verbose_name='\u7236\u7ea7\u83dc\u5355')),
            ],
            options={
                'db_table': 'larryMenus',
                'verbose_name': 'larryMenus',
                'verbose_name_plural': 'larryMenus',
            },
        ),
    ]
