# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_larrymenus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='larrymenus',
            name='font',
            field=models.CharField(blank=True, default='larry-icon', max_length=32, null=True, verbose_name='\u5b57\u4f53'),
        ),
        migrations.AlterField(
            model_name='larrymenus',
            name='icon',
            field=models.CharField(blank=True, default='larry-widgets', max_length=32, null=True, verbose_name='\u56fe\u6807'),
        ),
    ]
