# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20180830_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='larrymenus',
            name='priority',
            field=models.IntegerField(blank=True, help_text='\u83dc\u5355\u7684\u663e\u793a\u987a\u5e8f,\u4f18\u5148\u7ea7\u8d8a\u5927\u663e\u793a\u8d8a\u9760\u524d', null=True, verbose_name='\u663e\u793a\u4f18\u5148\u7ea7'),
        ),
        migrations.AddField(
            model_name='larrymenus',
            name='show',
            field=models.NullBooleanField(default=False, help_text='\u83dc\u5355\u662f\u5426\u663e\u793a\uff0c\u9ed8\u8ba4\u4e0d\u663e\u793a', verbose_name='\u662f\u5426\u663e\u793a'),
        ),
    ]
