# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20180830_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u89d2\u8272\u63cf\u8ff0'),
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=True, verbose_name='\u89d2\u8272\u72b6\u6001'),
        ),
    ]
