# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20180903_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100, verbose_name='\u90e8\u7f72\u7ad9\u70b9')),
                ('host', models.CharField(max_length=100, verbose_name='\u90ae\u4ef6\u53d1\u9001\u670d\u52a1\u5668')),
                ('port', models.SmallIntegerField(verbose_name='\u90ae\u4ef6\u53d1\u9001\u670d\u52a1\u5668\u7aef\u53e3')),
                ('user', models.CharField(max_length=100, verbose_name='\u53d1\u9001\u7528\u6237\u8d26\u6237')),
                ('passwd', models.CharField(max_length=100, verbose_name='\u53d1\u9001\u7528\u6237\u5bc6\u7801')),
                ('subject', models.CharField(default='[OPS]', max_length=100, verbose_name='\u53d1\u9001\u90ae\u4ef6\u4e3b\u9898\u6807\u8bc6')),
                ('cc_user', models.TextField(blank=True, null=True, verbose_name='\u6284\u9001\u7528\u6237\u5217\u8868')),
            ],
            options={
                'db_table': 'opsmanage_email_config',
            },
        ),
        migrations.CreateModel(
            name='Global_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansible_model', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542fansible\u6a21\u5757\u64cd\u4f5c\u8bb0\u5f55')),
                ('ansible_playbook', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542fansible\u5267\u672c\u64cd\u4f5c\u8bb0\u5f55')),
                ('cron', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542f\u8ba1\u5212\u4efb\u52a1\u64cd\u4f5c\u8bb0\u5f55')),
                ('project', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542f\u9879\u76ee\u64cd\u4f5c\u8bb0\u5f55')),
                ('assets', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542f\u8d44\u4ea7\u64cd\u4f5c\u8bb0\u5f55')),
                ('server', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542f\u670d\u52a1\u5668\u547d\u4ee4\u8bb0\u5f55')),
                ('email', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542f\u90ae\u4ef6\u901a\u77e5')),
                ('webssh', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542fWebSSH')),
                ('sql', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542fSQL\u66f4\u65b0\u901a\u77e5')),
            ],
            options={
                'db_table': 'opsmanage_global_config',
            },
        ),
        migrations.CreateModel(
            name='Server_Command_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='\u8fdc\u7a0b\u7528\u6237')),
                ('server', models.CharField(max_length=50, verbose_name='\u670d\u52a1\u5668IP')),
                ('client', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5ba2\u6237\u673aIP')),
                ('command', models.TextField(blank=True, null=True, verbose_name='\u5386\u53f2\u547d\u4ee4')),
                ('etime', models.CharField(max_length=50, unique=True, verbose_name='\u547d\u4ee4\u6267\u884c\u65f6\u95f4')),
            ],
            options={
                'db_table': 'opsmanage_server_command_record',
                'verbose_name': '\u670d\u52a1\u5668\u64cd\u4f5c\u65e5\u5fd7\u8868',
                'verbose_name_plural': '\u670d\u52a1\u5668\u64cd\u4f5c\u65e5\u5fd7\u8868',
                'permissions': (('can_read_server_command_record', '\u8bfb\u53d6\u670d\u52a1\u5668\u64cd\u4f5c\u65e5\u5fd7\u6743\u9650'), ('can_change_server_command_record', '\u66f4\u6539\u670d\u52a1\u5668\u64cd\u4f5c\u65e5\u5fd7\u6743\u9650'), ('can_add_server_command_record', '\u6dfb\u52a0\u670d\u52a1\u5668\u64cd\u4f5c\u65e5\u5fd7\u6743\u9650'), ('can_delete_server_command_record', '\u5220\u9664\u670d\u52a1\u5668\u64cd\u4f5c\u65e5\u5fd7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='User_Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.SmallIntegerField(verbose_name='\u670d\u52a1\u5668\u8d44\u4ea7id')),
                ('user_id', models.SmallIntegerField(verbose_name='\u7528\u6237id')),
            ],
            options={
                'verbose_name_plural': '\u7528\u6237\u670d\u52a1\u5668\u8868',
                'db_table': 'opsmanage_user_server',
                'verbose_name': '\u7528\u6237\u670d\u52a1\u5668\u8868',
                'permissions': (('can_read_user_server', '\u8bfb\u53d6\u7528\u6237\u670d\u52a1\u5668\u8868\u6743\u9650'), ('can_change_user_server', '\u66f4\u6539\u7528\u6237\u670d\u52a1\u5668\u8868\u6743\u9650'), ('can_add_user_server', '\u6dfb\u52a0\u7528\u6237\u670d\u52a1\u5668\u8868\u6743\u9650'), ('can_delete_user_server', '\u5220\u9664\u7528\u6237\u670d\u52a1\u5668\u8868\u6743\u9650')),
            },
        ),
        migrations.AlterUniqueTogether(
            name='user_server',
            unique_together=set([('server_id', 'user_id')]),
        ),
    ]
