# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-05 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
        ('system', '0008_auto_20180904_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownload_Audit_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_content', models.TextField(verbose_name='\u5de5\u5355\u7533\u8bf7\u5185\u5bb9')),
                ('dest_server', models.TextField(verbose_name='\u76ee\u6807\u670d\u52a1\u5668')),
                ('dest_path', models.CharField(max_length=200, verbose_name='\u6587\u4ef6\u8def\u5f84')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Orders.Order_System')),
            ],
            options={
                'db_table': 'opsmanage_filedownload_audit_order',
                'verbose_name': '\u6587\u4ef6\u4e0a\u4f20\u5ba1\u6838\u5de5\u5355\u8868',
                'verbose_name_plural': '\u6587\u4ef6\u4e0b\u8f7d\u5ba1\u6838\u5de5\u5355\u8868',
                'permissions': (('can_read_filedownload_audit_order', '\u8bfb\u53d6\u6587\u4ef6\u4e0b\u8f7d\u5ba1\u6838\u5de5\u5355\u6743\u9650'), ('can_change_filedownload_audit_order', '\u66f4\u6539\u6587\u4ef6\u4e0b\u8f7d\u5ba1\u6838\u5de5\u5355\u6743\u9650'), ('can_add_filedownload_audit_order', '\u6dfb\u52a0\u6587\u4ef6\u4e0b\u8f7d\u5ba1\u6838\u5de5\u5355\u6743\u9650'), ('can_delete_filedownload_audit_order', '\u5220\u9664\u6587\u4ef6\u4e0b\u8f7d\u5ba1\u6838\u5de5\u5355\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='FileUpload_Audit_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_path', models.CharField(max_length=200, verbose_name='\u76ee\u6807\u670d\u52a1\u5668\u6587\u4ef6\u8def\u5f84')),
                ('order_content', models.TextField(verbose_name='\u5de5\u5355\u7533\u8bf7\u5185\u5bb9')),
                ('dest_server', models.TextField(verbose_name='\u76ee\u6807\u670d\u52a1\u5668')),
                ('chown_user', models.CharField(max_length=100, verbose_name='\u6587\u4ef6\u5bbf\u4e3b')),
                ('chown_rwx', models.CharField(max_length=100, verbose_name='\u6587\u4ef6\u6743\u9650')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Orders.Order_System')),
            ],
            options={
                'db_table': 'opsmanage_fileupload_audit_order',
                'verbose_name': '\u6587\u4ef6\u4e0a\u4f20\u5ba1\u6838\u5de5\u5355\u8868',
                'verbose_name_plural': '\u6587\u4ef6\u4e0a\u4f20\u5ba1\u6838\u5de5\u5355\u8868',
                'permissions': (('can_read_fileupload_audit_order', '\u8bfb\u53d6\u6587\u4ef6\u4e0a\u4f20\u5ba1\u6838\u5de5\u5355\u6743\u9650'), ('can_change_fileupload_audit_order', '\u66f4\u6539\u6587\u4ef6\u4e0a\u4f20\u5ba1\u6838\u5de5\u5355\u6743\u9650'), ('can_add_fileupload_audit_order', '\u6dfb\u52a0\u6587\u4ef6\u4e0a\u4f20\u5ba1\u6838\u5de5\u5355\u6743\u9650'), ('can_delete_fileupload_audit_order', '\u5220\u9664\u6587\u4ef6\u4e0a\u4f20\u5ba1\u6838\u5de5\u5355\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(max_length=500, upload_to='./file/upload/%Y%m%d%H%M%S', verbose_name='\u6587\u4ef6\u4e0a\u4f20\u8def\u5f84')),
                ('file_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6587\u4ef6\u7c7b\u578b')),
                ('file_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='system.FileUpload_Audit_Order')),
            ],
            options={
                'db_table': 'opsmanage_uploadfiles',
            },
        ),
    ]
