# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_filedownload_audit_order_fileupload_audit_order_uploadfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.SmallIntegerField(verbose_name='\u670d\u52a1\u5668\u8d44\u4ea7id')),
                ('user_id', models.SmallIntegerField(verbose_name='\u7528\u6237id')),
            ],
            options={
                'verbose_name_plural': '\u7528\u6237\u670d\u52a1\u5668\u8868',
                'db_table': 'user_host',
                'verbose_name': '\u7528\u6237\u670d\u52a1\u5668\u8868',
                'permissions': (('can_read_user_host', '\u8bfb\u53d6\u7528\u6237\u670d\u52a1\u5668\u8868\u6743\u9650'), ('can_change_user_host', '\u66f4\u6539\u7528\u6237\u670d\u52a1\u5668\u8868\u6743\u9650'), ('can_add_user_host', '\u6dfb\u52a0\u7528\u6237\u670d\u52a1\u5668\u8868\u6743\u9650'), ('can_delete_user_host', '\u5220\u9664\u7528\u6237\u670d\u52a1\u5668\u8868\u6743\u9650')),
            },
        ),
        migrations.AlterUniqueTogether(
            name='user_host',
            unique_together=set([('host_id', 'user_id')]),
        ),
    ]
