# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20181113_1915'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='global_config',
            table='global_config',
        ),
    ]
