# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20181114_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='parent',
        ),
        migrations.DeleteModel(
            name='User_Server',
        ),
        migrations.AlterField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(to='system.LarryMenus'),
        ),
        migrations.AlterModelTable(
            name='email_config',
            table='email_config',
        ),
        migrations.AlterModelTable(
            name='filedownload_audit_order',
            table='filedownload_audit_order',
        ),
        migrations.AlterModelTable(
            name='fileupload_audit_order',
            table='fileupload_audit_order',
        ),
        migrations.AlterModelTable(
            name='server_command_record',
            table='server_command_record',
        ),
        migrations.AlterModelTable(
            name='uploadfiles',
            table='uploadfiles',
        ),
        migrations.DeleteModel(
            name='Menus',
        ),
    ]
