# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='wiki_category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='wiki_comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='wiki_post',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='wiki_tag',
        ),
    ]
