# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [



    ]
