# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_High_Risk_SQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.CharField(max_length=200, unique=True, verbose_name=b'SQL\xe5\x86\x85\xe5\xae\xb9')),
            ],
            options={
                'db_table': 'opsmanage_custom_high_risk_sql',
                'verbose_name': '\u81ea\u5b9a\u4e49\u9ad8\u5371SQL\u8868',
                'verbose_name_plural': '\u81ea\u5b9a\u4e49\u9ad8\u5371SQL\u8868',
                'permissions': (('can_read_custom_high_risk_sql', '\u8bfb\u53d6\u9ad8\u5371SQL\u8868\u6743\u9650'), ('can_change_custom_high_risk_sql', '\u66f4\u6539\u9ad8\u5371SQL\u8868\u6743\u9650'), ('can_add_custom_high_risk_sql', '\u6dfb\u52a0\u9ad8\u5371SQL\u8868\u6743\u9650'), ('can_delete_custom_high_risk_sql', '\u5220\u9664\u9ad8\u5371SQL\u8868\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='DataBase_Server_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_env', models.CharField(choices=[(b'test', '\u6d4b\u8bd5\u73af\u5883'), (b'prod', '\u751f\u4ea7\u73af\u5883')], default=None, max_length=10, verbose_name=b'\xe7\x8e\xaf\xe5\xa2\x83\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('db_type', models.CharField(default=None, max_length=10, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('db_name', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe5\x90\x8d')),
                ('db_host', models.CharField(max_length=100, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe5\x9c\xb0\xe5\x9d\x80')),
                ('db_mode', models.SmallIntegerField(choices=[(b'1', '\u5355\u4f8b'), (b'2', '\u4e3b\u4ece'), (b'3', 'pxc')], default=1, verbose_name=b'\xe6\x9e\xb6\xe6\x9e\x84\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('db_user', models.CharField(max_length=100, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
                ('db_passwd', models.CharField(max_length=100, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81')),
                ('db_port', models.IntegerField(verbose_name=b'\xe7\xab\xaf\xe5\x8f\xa3')),
                ('db_group', models.SmallIntegerField(verbose_name=b'\xe4\xbd\xbf\xe7\x94\xa8\xe7\xbb\x84')),
                ('db_service', models.SmallIntegerField(verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('db_project', models.SmallIntegerField(verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe9\xa1\xb9\xe7\x9b\xae')),
                ('db_mark', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe6\xa0\x87\xe8\xaf\x86')),
            ],
            options={
                'verbose_name_plural': '\u6570\u636e\u5e93\u4fe1\u606f\u8868',
                'db_table': 'opsmanage_database_server_config',
                'verbose_name': '\u6570\u636e\u5e93\u4fe1\u606f\u8868',
                'permissions': (('can_read_database_server_config', '\u8bfb\u53d6\u6570\u636e\u5e93\u4fe1\u606f\u8868\u6743\u9650'), ('can_change_database_server_config', '\u66f4\u6539\u6570\u636e\u5e93\u4fe1\u606f\u8868\u6743\u9650'), ('can_add_database_server_config', '\u6dfb\u52a0\u6570\u636e\u5e93\u4fe1\u606f\u8868\u6743\u9650'), ('can_delete_database_server_config', '\u5220\u9664\u6570\u636e\u5e93\u4fe1\u606f\u8868\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Inception_Server_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe5\x90\x8d')),
                ('db_host', models.CharField(max_length=100, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe5\x9c\xb0\xe5\x9d\x80')),
                ('db_user', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
                ('db_passwd', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81')),
                ('db_backup_host', models.CharField(max_length=100, verbose_name=b'\xe5\xa4\x87\xe4\xbb\xbd\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe5\x9c\xb0\xe5\x9d\x80')),
                ('db_backup_user', models.CharField(max_length=100, verbose_name=b'\xe5\xa4\x87\xe4\xbb\xbd\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe8\xb4\xa6\xe6\x88\xb7')),
                ('db_backup_passwd', models.CharField(max_length=100, verbose_name=b'\xe5\xa4\x87\xe4\xbb\xbd\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe5\xaf\x86\xe7\xa0\x81')),
                ('db_backup_port', models.SmallIntegerField(verbose_name=b'\xe5\xa4\x87\xe4\xbb\xbd\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe7\xab\xaf\xe5\x8f\xa3')),
                ('db_port', models.SmallIntegerField(verbose_name=b'\xe7\xab\xaf\xe5\x8f\xa3')),
            ],
            options={
                'db_table': 'opsmanage_inception_server_config',
                'verbose_name': 'inception\u4fe1\u606f\u8868',
                'verbose_name_plural': 'inception\u4fe1\u606f\u8868',
                'permissions': (('can_read_inception_server_config', '\u8bfb\u53d6inception\u4fe1\u606f\u8868\u6743\u9650'), ('can_change_inception_server_config', '\u66f4\u6539inception\u4fe1\u606f\u8868\u6743\u9650'), ('can_add_inception_server_config', '\u6dfb\u52a0inception\u4fe1\u606f\u8868\u6743\u9650'), ('can_delete_inception_server_config', '\u5220\u9664inception\u4fe1\u606f\u8868\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='SQL_Audit_Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_auto_audit', models.SmallIntegerField(blank=True, null=True, verbose_name=b'\xe6\xb5\x8b\xe8\xaf\x95\xe7\x8e\xaf\xe5\xa2\x83\xe8\x87\xaa\xe5\x8a\xa8\xe6\x8e\x88\xe6\x9d\x83')),
                ('t_backup_sql', models.SmallIntegerField(blank=True, null=True, verbose_name=b'\xe6\xb5\x8b\xe8\xaf\x95\xe7\x8e\xaf\xe5\xa2\x83\xe8\x87\xaa\xe5\x8a\xa8\xe5\xa4\x87\xe4\xbb\xbdSQL')),
                ('t_email', models.SmallIntegerField(blank=True, null=True, verbose_name=b'\xe6\xb5\x8b\xe8\xaf\x95\xe7\x8e\xaf\xe5\xa2\x83\xe5\xbc\x80\xe5\x90\xaf\xe9\x82\xae\xe4\xbb\xb6\xe9\x80\x9a\xe7\x9f\xa5')),
                ('p_auto_audit', models.SmallIntegerField(blank=True, null=True, verbose_name=b'\xe6\xad\xa3\xe5\xbc\x8f\xe7\x8e\xaf\xe5\xa2\x83\xe8\x87\xaa\xe5\x8a\xa8\xe6\x8e\x88\xe6\x9d\x83')),
                ('p_backup_sql', models.SmallIntegerField(blank=True, null=True, verbose_name=b'\xe6\xad\xa3\xe5\xbc\x8f\xe7\x8e\xaf\xe5\xa2\x83\xe8\x87\xaa\xe5\x8a\xa8\xe5\xa4\x87\xe4\xbb\xbdSQL')),
                ('p_email', models.SmallIntegerField(blank=True, null=True, verbose_name=b'\xe6\xad\xa3\xe5\xbc\x8f\xe7\x8e\xaf\xe5\xa2\x83\xe5\xbc\x80\xe5\x90\xaf\xe9\x82\xae\xe4\xbb\xb6\xe9\x80\x9a\xe7\x9f\xa5')),
                ('audit_group', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe5\xae\xa1\xe6\xa0\xb8\xe7\xbb\x84')),
            ],
            options={
                'db_table': 'opsmanage_sql_audit_control',
                'verbose_name': 'SQL\u5ba1\u6838\u914d\u7f6e',
                'verbose_name_plural': 'SQL\u5ba1\u6838\u914d\u7f6e',
                'permissions': (('can_read_sql_audit_control', '\u8bfb\u53d6SQL\u5ba1\u6838\u914d\u7f6e\u8868\u6743\u9650'), ('can_change_sql_audit_control', '\u66f4\u6539SQL\u5ba1\u6838\u914d\u7f6e\u8868\u6743\u9650'), ('can_add_sql_audit_control', '\u6dfb\u52a0SQL\u5ba1\u6838\u914d\u7f6e\u6743\u9650'), ('can_delete_sql_audit_control', '\u5220\u9664SQL\u5ba1\u6838\u914d\u7f6e\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='SQL_Execute_Histroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exe_user', models.CharField(max_length=100, verbose_name=b'\xe6\x89\xa7\xe8\xa1\x8c\xe4\xba\xba')),
                ('exe_sql', models.TextField(verbose_name=b'\xe6\x89\xa7\xe8\xa1\x8c\xe7\x9a\x84SQL\xe5\x86\x85\xe5\xae\xb9')),
                ('exec_status', models.SmallIntegerField(blank=True, null=True, verbose_name=b'\xe6\x89\xa7\xe8\xa1\x8c\xe7\x8a\xb6\xe6\x80\x81')),
                ('exe_result', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x89\xa7\xe8\xa1\x8c\xe7\xbb\x93\xe6\x9e\x9c')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'\xe6\x89\xa7\xe8\xa1\x8c\xe6\x97\xb6\xe9\x97\xb4')),
                ('exe_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MysqlOps.DataBase_Server_Config', verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93id')),
            ],
            options={
                'db_table': 'opsmanage_sql_execute_histroy',
                'verbose_name': 'SQL\u6267\u884c\u5386\u53f2\u8bb0\u5f55\u8868',
                'verbose_name_plural': 'SQL\u6267\u884c\u5386\u53f2\u8bb0\u5f55\u8868',
                'permissions': (('can_read_sql_execute_histroy', '\u8bfb\u53d6SQL\u6267\u884c\u5386\u53f2\u8868\u6743\u9650'), ('can_change_sql_execute_histroy', '\u66f4\u6539SQL\u6267\u884c\u5386\u53f2\u8868\u6743\u9650'), ('can_add_sql_execute_histroy', '\u6dfb\u52a0SQL\u6267\u884c\u5386\u53f2\u8868\u6743\u9650'), ('can_delete_sql_execute_histroy', '\u5220\u9664SQL\u6267\u884c\u5386\u53f2\u8868\u6743\u9650')),
            },
        ),
        migrations.AlterUniqueTogether(
            name='database_server_config',
            unique_together=set([('db_port', 'db_host', 'db_env', 'db_name')]),
        ),
    ]
