# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MysqlOps', '0002_binlogparseredo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinlogParseUndo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.CharField(blank=True, max_length=1900, null=True, verbose_name=b'\xe9\x80\x86\xe5\x90\x91\xe8\xa7\xa3\xe6\x9e\x90\xe5\x90\x8e\xe7\x9a\x84sql')),
                ('start_pos', models.IntegerField(blank=True, null=True, verbose_name=b'\xe8\xb5\xb7\xe5\xa7\x8b\xe4\xbd\x8d\xe7\xbd\xae')),
                ('end_pos', models.IntegerField(blank=True, null=True, verbose_name=b'\xe7\xbb\x93\xe6\x9d\x9f\xe4\xbd\x8d\xe7\xbd\xae')),
                ('date', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe6\x89\xa7\xe8\xa1\x8c\xe6\x97\xa5\xe6\x9c\x9f')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe6\x89\xa7\xe8\xa1\x8c\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'db_table': 'binlogParseUndo',
                'verbose_name': 'bin\u65e5\u5fd7\u9006\u5411\u89e3\u6790',
                'verbose_name_plural': 'bin\u65e5\u5fd7\u9006\u5411\u89e3\u6790',
            },
        ),
    ]
