# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MysqlOps', '0004_auto_20181107_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binlogparseundo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='binlogparseundo',
            name='time',
        ),
        migrations.AddField(
            model_name='binlogparseundo',
            name='datetime',
            field=models.DateTimeField(blank=True, max_length=50, null=True, verbose_name=b'\xe6\x89\xa7\xe8\xa1\x8c\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
