# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MysqlOps', '0005_auto_20181107_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binlogparseundo',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
