# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MysqlOps', '0006_auto_20181107_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binlogparseundo',
            name='date_time',
        ),
        migrations.AddField(
            model_name='binlogparseundo',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe6\x89\xa7\xe8\xa1\x8c\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AddField(
            model_name='binlogparseundo',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe6\x89\xa7\xe8\xa1\x8c\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
