# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MysqlOps', '0007_auto_20181107_1051'),
    ]

    operations = [

    ]
