# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MysqlOps', '0008_auto_20181204_1647'),
    ]

    operations = [

    ]
