# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MysqlOps', '0009_auto_20181207_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_High_Risk_SQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.CharField(max_length=200, unique=True, verbose_name=b'SQL\xe5\x86\x85\xe5\xae\xb9')),
            ],
            options={
                'db_table': 'custom_high_risk_sql',
                'verbose_name': '\u81ea\u5b9a\u4e49\u9ad8\u5371SQL\u8868',
                'verbose_name_plural': '\u81ea\u5b9a\u4e49\u9ad8\u5371SQL\u8868',
                'permissions': (('can_read_custom_high_risk_sql', '\u8bfb\u53d6\u9ad8\u5371SQL\u8868\u6743\u9650'), ('can_change_custom_high_risk_sql', '\u66f4\u6539\u9ad8\u5371SQL\u8868\u6743\u9650'), ('can_add_custom_high_risk_sql', '\u6dfb\u52a0\u9ad8\u5371SQL\u8868\u6743\u9650'), ('can_delete_custom_high_risk_sql', '\u5220\u9664\u9ad8\u5371SQL\u8868\u6743\u9650')),
            },
        ),
    ]
