# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-24 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MysqlOps', '0010_custom_high_risk_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binlogparseredo',
            name='sql',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name=b'\xe8\xa7\xa3\xe6\x9e\x90\xe5\x90\x8e\xe7\x9a\x84sql'),
        ),
        migrations.AlterField(
            model_name='binlogparseundo',
            name='sql',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name=b'\xe9\x80\x86\xe5\x90\x91\xe8\xa7\xa3\xe6\x9e\x90\xe5\x90\x8e\xe7\x9a\x84sql'),
        ),
    ]
