# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-06 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MysqlOps', '0011_auto_20181224_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlFastSQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'sql\xe5\x90\x8d\xe5\xad\x97')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xe8\xaf\xb4\xe6\x98\x8e\xe6\x96\x87\xe5\xad\x97')),
                ('sql', models.CharField(max_length=1000, verbose_name=b'sql \xe8\xaf\xad\xe5\x8f\xa5\xe8\xaf\xb7\xe8\x87\xaa\xe5\xb7\xb1\xe9\xaa\x8c\xe8\xaf\x81\xe6\xad\xa3\xe7\xa1\xae')),
                ('exec_post', models.CharField(blank=True, choices=[('\u4e3b\u5e93', '\u4e3b\u5e93'), ('\u4ece\u5e93', '\u4ece\u5e93'), ('\u96c6\u7fa4', '\u96c6\u7fa4')], max_length=30, null=True, verbose_name='\u6267\u884c\u4f4d\u7f6e')),
            ],
        ),
    ]
