# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MysqlOps', '0012_mysqlfastsql'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysqlfastsql',
            old_name='exec_post',
            new_name='exec_posi',
        ),
    ]
