# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('type', models.CharField(choices=[('DX', '\u7535\u4fe1'), ('LT', '\u8054\u901a'), ('YD', '\u79fb\u52a8'), ('ZJ', '\u81ea\u5efa'), ('BGP', 'BGP')], default='BGP', max_length=20, verbose_name='\u673a\u623f\u7c7b\u578b')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='\u673a\u623f\u5730\u5740')),
                ('tel', models.CharField(max_length=30, null=True, verbose_name='\u673a\u623f\u7535\u8bdd')),
                ('contact', models.CharField(max_length=30, null=True, verbose_name='\u5ba2\u6237\u7ecf\u7406')),
                ('contact_phone', models.CharField(max_length=30, null=True, verbose_name='\u79fb\u52a8\u7535\u8bdd')),
                ('jigui', models.CharField(max_length=30, null=True, verbose_name='\u673a\u67dc\u4fe1\u606f')),
                ('ip_range', models.CharField(max_length=30, null=True, verbose_name='IP\u8303\u56f4')),
                ('bandwidth', models.CharField(max_length=30, null=True, verbose_name='\u63a5\u5165\u5e26\u5bbd')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='\u79df\u8d41\u65e5\u671f')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='\u5230\u671f\u65e5\u671f')),
                ('cost', models.CharField(blank=True, max_length=20, verbose_name='\u79df\u8d41\u8d39\u7528')),
            ],
            options={
                'verbose_name': '\u6570\u636e\u4e2d\u5fc3',
                'verbose_name_plural': '\u6570\u636e\u4e2d\u5fc3',
            },
        ),
        migrations.CreateModel(
            name='InterFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vendor', models.CharField(max_length=30, null=True)),
                ('bandwidth', models.CharField(max_length=30, null=True)),
                ('tel', models.CharField(max_length=30, null=True)),
                ('contact', models.CharField(max_length=30, null=True)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('price', models.IntegerField(verbose_name='\u4ef7\u683c')),
            ],
        ),
        migrations.CreateModel(
            name='IpSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net', models.CharField(max_length=30)),
                ('subnet', models.CharField(max_length=30, null=True)),
                ('describe', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicename', models.CharField(max_length=50, unique=True, verbose_name='\u8bbe\u5907\u540d')),
                ('in_band_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u5e26\u5185IP')),
                ('out_band_ip', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5e26\u5916IP')),
                ('in_net_ip', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4e92\u8054IP')),
                ('asset_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('asset_type', models.CharField(blank=True, choices=[(b'1', '\u8def\u7531\u5668'), (b'2', '\u4ea4\u6362\u673a'), (b'3', '\u9632\u706b\u5899'), (b'4', '\u52a0\u5bc6\u673a')], max_length=30, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('status', models.CharField(blank=True, choices=[(b'1', '\u4f7f\u7528\u4e2d'), (b'2', '\u672a\u4f7f\u7528'), (b'3', '\u6545\u969c'), (b'4', '\u5176\u5b83')], default='1', max_length=30, null=True, verbose_name='\u4f7f\u7528\u72b6\u6001')),
                ('brand', models.CharField(blank=True, choices=[(b'1', 'juniper'), (b'2', '\u534e\u4e09'), (b'3', '\u534e\u4e3a'), (b'4', '\u601d\u79d1'), (b'5', '\u535a\u79d1'), (b'6', '\u6df1\u4fe1\u670d'), (b'7', 'IBM'), (b'8', 'TP-LINK'), (b'9', '\u9510\u6377')], max_length=50, null=True, verbose_name='\u54c1\u724c')),
                ('brand_model', models.CharField(blank=True, max_length=150, null=True, verbose_name='\u578b\u53f7')),
                ('sn', models.CharField(blank=True, max_length=60, null=True, verbose_name='SN\u53f7 \u7801')),
                ('cabinet', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u673a\u67dc')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u673a\u67b6')),
                ('useuser', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7ba1\u7406\u5458')),
                ('purpose', models.CharField(blank=True, max_length=140, verbose_name='\u7528\u9014')),
                ('soft_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8f6f\u4ef6\u7248\u672c')),
                ('url', models.URLField(blank=True, max_length=100, verbose_name='\u8bbf\u95eeURL')),
                ('username', models.CharField(blank=True, max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='\u5bc6\u7801')),
                ('onlinedate', models.DateField(blank=True, default='2018-01-01', max_length=50, null=True, verbose_name='\u4e0a\u7ebf\u65f6\u95f4')),
                ('memo', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
        ),
        migrations.CreateModel(
            name='NetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u7ec4\u540d')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.AddField(
            model_name='netdevice',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.NetGroup', verbose_name='\u8bbe\u5907\u7ec4'),
        ),
        migrations.AddField(
            model_name='netdevice',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.Idc', verbose_name='\u6240\u5728\u673a\u623f'),
        ),
    ]
