# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0002_mysqlcluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mysql_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.CharField(max_length=50, verbose_name='\u6570\u636e\u5e93\u6216\u8868\u7a7a\u95f4\u540d')),
                ('db_size', models.CharField(max_length=50, verbose_name='\u5e93\u5927\u5c0f')),
                ('dbcluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.MySQLCluster', verbose_name='\u6240\u5c5e\u96c6\u7fa4')),
            ],
            options={
                'db_table': 'MySQL_DB',
                'verbose_name': 'mysql\u5185\u90e8DB',
                'verbose_name_plural': 'mysql\u5185\u90e8DB',
            },
        ),
    ]
