# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0002_auto_20180917_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlcluster',
            name='down_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u4e0b\u7ebf\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='mysqlcluster',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='mysqlcluster',
            name='up_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u4e0a\u7ebf\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='mysqlcluster',
            name='arch',
            field=models.CharField(blank=True, choices=[('\u4e3b\u4ece', '\u4e3b\u4ece'), ('\u5355\u5e93', '\u5355\u5e93'), ('innodb_cluster', 'innodb_cluster'), ('PXC', 'PXC')], max_length=30, null=True, verbose_name='\u96c6\u7fa4\u67b6\u6784'),
        ),
    ]
