# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0002_auto_20180816_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u4ea7\u54c1\u7ebf\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4ea7\u54c1\u7ebf\u63cf\u8ff0')),
                ('incharger', models.CharField(max_length=50, unique=True, verbose_name='\u8d1f\u8d23\u4eba\u59d3\u540d')),
                ('phone', models.CharField(max_length=50, verbose_name='\u8d1f\u8d23\u4eba\u624b\u673a')),
                ('qq', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8d1f\u8d23\u4ebaQQ')),
                ('weChat', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8d1f\u8d23\u4eba\u5fae\u4fe1')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='\u8d1f\u8d23\u4eba\u90ae\u7bb1')),
            ],
        ),
    ]
