# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0003_productline'),
    ]

    operations = [
    ]
