# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-11 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0003_mysql_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySQL_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbtag', models.CharField(max_length=50, unique=True, verbose_name='\u6570\u636e\u5e93\u5b9e\u4f8b\u6807\u7b7e')),
                ('vist_ip', models.GenericIPAddressField(verbose_name='\u8bbf\u95eeIP')),
                ('m_ip', models.GenericIPAddressField(verbose_name='\u7ba1\u7406IP')),
                ('port', models.CharField(max_length=5, verbose_name='\u7aef\u53e3')),
                ('master_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u4ed6\u7684\u4e3b\u5e93IP')),
                ('master_port', models.CharField(blank=True, max_length=6, null=True, verbose_name='\u4ed6\u7684\u4e3b\u5e93\u7aef\u53e3')),
                ('idc', models.CharField(blank=True, max_length=6, null=True, verbose_name='\u673a\u623f')),
                ('role', models.CharField(blank=True, choices=[('\u5355\u5e93', '\u5355\u5e93'), ('\u4e3b\u5e93', '\u4e3b\u5e93'), ('\u4ece\u5e93', '\u4ece\u5e93'), ('\u6c47\u603b', '\u6c47\u603b')], max_length=50, null=True, verbose_name='DB\u89d2\u8272')),
                ('db_status', models.CharField(blank=True, choices=[('\u4f7f\u7528\u4e2d', '\u4f7f\u7528\u4e2d'), ('\u672a\u4f7f\u7528', '\u672a\u4f7f\u7528'), ('\u6545\u969c', '\u6545\u969c'), ('\u5176\u5b83', '\u5176\u5b83')], max_length=30, null=True, verbose_name='DB\u72b6\u6001')),
                ('memory', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5206\u914d\u5185\u5b58')),
                ('disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u78c1\u76d8\u4f4d\u7f6e')),
                ('memo', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('dbcluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CMDB.MySQLCluster', verbose_name='\u6570\u636e\u5e93\u96c6\u7fa4')),
            ],
            options={
                'db_table': 'MySQL_Instance',
                'verbose_name': 'mysql\u96c6\u7fa4\u4e00\u4e2a\u5b9e\u4f8b',
                'verbose_name_plural': 'mysql\u96c6\u7fa4\u4e00\u4e2a\u5b9e\u4f8b',
            },
        ),
    ]
