# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0003_auto_20180917_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlcluster',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u96c6\u7fa4\u5bf9\u5916\u57df\u540d'),
        ),
        migrations.AddField(
            model_name='mysqlcluster',
            name='foreign_port',
            field=models.IntegerField(blank=True, max_length=6, null=True, verbose_name='\u96c6\u7fa4\u5bf9\u5916\u7aef\u53e3'),
        ),
    ]
