# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0004_auto_20180917_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql_instance',
            name='db_status',
            field=models.CharField(blank=True, choices=[('\u4f7f\u7528\u4e2d', '\u4f7f\u7528\u4e2d'), ('\u672a\u5bf9\u5916', '\u672a\u5bf9\u5916'), ('\u6545\u969c', '\u6545\u969c'), ('\u5176\u4ed6', '\u5176\u4ed6')], max_length=30, null=True, verbose_name='DB\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='mysql_instance',
            name='vist_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='\u8bbf\u95eeIP'),
        ),
        migrations.AlterField(
            model_name='mysqlcluster',
            name='foreign_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u96c6\u7fa4\u5bf9\u5916\u7aef\u53e3'),
        ),
    ]
