# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0004_auto_20180817_2327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterFace',
        ),
        migrations.DeleteModel(
            name='IpSource',
        ),
        migrations.RemoveField(
            model_name='netdevice',
            name='group',
        ),
        migrations.RemoveField(
            model_name='netdevice',
            name='idc',
        ),
        migrations.DeleteModel(
            name='Idc',
        ),
        migrations.DeleteModel(
            name='NetDevice',
        ),
        migrations.DeleteModel(
            name='NetGroup',
        ),
    ]
