# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 00:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CMDB', '0005_auto_20180817_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('type', models.CharField(choices=[('DX', '\u7535\u4fe1'), ('LT', '\u8054\u901a'), ('YD', '\u79fb\u52a8'), ('ZJ', '\u81ea\u5efa'), ('BGP', 'BGP')], default='BGP', max_length=20, verbose_name='\u673a\u623f\u7c7b\u578b')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='\u673a\u623f\u5730\u5740')),
                ('tel', models.CharField(max_length=30, null=True, verbose_name='\u673a\u623f\u7535\u8bdd')),
                ('contact', models.CharField(max_length=30, null=True, verbose_name='\u5ba2\u6237\u7ecf\u7406')),
                ('contact_phone', models.CharField(max_length=30, null=True, verbose_name='\u79fb\u52a8\u7535\u8bdd')),
                ('jigui', models.CharField(max_length=30, null=True, verbose_name='\u673a\u67dc\u4fe1\u606f')),
                ('ip_range', models.CharField(max_length=30, null=True, verbose_name='IP\u8303\u56f4')),
                ('bandwidth', models.CharField(max_length=30, null=True, verbose_name='\u63a5\u5165\u5e26\u5bbd')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='\u79df\u8d41\u65e5\u671f')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='\u5230\u671f\u65e5\u671f')),
                ('cost', models.CharField(blank=True, max_length=20, verbose_name='\u79df\u8d41\u8d39\u7528')),
            ],
            options={
                'verbose_name': '\u6570\u636e\u4e2d\u5fc3',
                'verbose_name_plural': '\u6570\u636e\u4e2d\u5fc3',
            },
        ),
        migrations.CreateModel(
            name='Mysql_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.CharField(max_length=50, verbose_name='\u6570\u636e\u5e93\u6216\u8868\u7a7a\u95f4\u540d')),
                ('db_size', models.CharField(max_length=50, verbose_name='\u5e93\u5927\u5c0f')),
            ],
            options={
                'db_table': 'MySQL_DB',
                'verbose_name': 'mysql\u5185\u90e8DB',
                'verbose_name_plural': 'mysql\u5185\u90e8DB',
            },
        ),
        migrations.CreateModel(
            name='MySQL_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbtag', models.CharField(max_length=50, unique=True, verbose_name='\u6570\u636e\u5e93\u5b9e\u4f8b\u6807\u7b7e')),
                ('vist_ip', models.GenericIPAddressField(verbose_name='\u8bbf\u95eeIP')),
                ('m_ip', models.GenericIPAddressField(verbose_name='\u7ba1\u7406IP')),
                ('port', models.CharField(max_length=5, verbose_name='\u7aef\u53e3')),
                ('master_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u4ed6\u7684\u4e3b\u5e93IP')),
                ('master_port', models.CharField(blank=True, max_length=6, null=True, verbose_name='\u4ed6\u7684\u4e3b\u5e93\u7aef\u53e3')),
                ('idc', models.CharField(blank=True, max_length=6, null=True, verbose_name='\u673a\u623f')),
                ('role', models.CharField(blank=True, choices=[('\u5355\u5e93', '\u5355\u5e93'), ('\u4e3b\u5e93', '\u4e3b\u5e93'), ('\u4ece\u5e93', '\u4ece\u5e93'), ('\u6c47\u603b', '\u6c47\u603b')], max_length=30, null=True, verbose_name='DB\u89d2\u8272')),
                ('db_status', models.CharField(blank=True, choices=[('\u4f7f\u7528\u4e2d', '\u4f7f\u7528\u4e2d'), ('\u672a\u4f7f\u7528', '\u672a\u4f7f\u7528'), ('\u6545\u969c', '\u6545\u969c'), ('\u5176\u5b83', '\u5176\u5b83')], max_length=30, null=True, verbose_name='DB\u72b6\u6001')),
                ('memory', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5206\u914d\u5185\u5b58')),
                ('disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u78c1\u76d8\u4f4d\u7f6e')),
                ('memo', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'MySQL_Instance',
                'verbose_name': 'mysql\u96c6\u7fa4\u4e00\u4e2a\u5b9e\u4f8b',
                'verbose_name_plural': 'mysql\u96c6\u7fa4\u4e00\u4e2a\u5b9e\u4f8b',
            },
        ),
        migrations.CreateModel(
            name='Mysql_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_user', models.CharField(blank=True, max_length=60, null=True)),
                ('db_password', models.CharField(blank=True, max_length=60, null=True)),
                ('privlige', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6743\u9650')),
            ],
            options={
                'db_table': 'MySQL_User',
                'verbose_name': 'mysql\u5185\u90e8\u7528\u6237',
                'verbose_name_plural': 'mysql\u5185\u90e8\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='MySQLCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u96c6\u7fa4\u540d')),
                ('arch', models.CharField(blank=True, choices=[('\u4e3b\u4ece', '\u4e3b\u4ece'), ('\u5355\u673a', '\u5355\u51fb'), ('innodb_cluster', 'innodb_cluster'), ('pxc', 'pxc')], max_length=30, null=True, verbose_name='\u96c6\u7fa4\u67b6\u6784')),
                ('db_version', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6570\u636e\u5e93\u7248\u672c')),
                ('defaultdb', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e3b\u7528DB')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
                ('operator', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='\u53ef\u89c1\u7684\u4eba')),
                ('tree_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.YewuTree', verbose_name='\u6240\u5c5e\u4ea7\u54c1\u7ebf')),
            ],
            options={
                'db_table': 'MySQL_Cluster',
                'verbose_name': 'mysql\u96c6\u7fa4',
                'verbose_name_plural': 'mysql\u96c6\u7fa4',
                'permissions': (('can_read_mysql_cluster', '\u8bfb\u53d6\u8d44\u4ea7\u6743\u9650'), ('can_change_mysql_cluster', '\u66f4\u6539\u8d44\u4ea7\u6743\u9650'), ('can_add_mysql_cluster', '\u6dfb\u52a0\u8d44\u4ea7\u6743\u9650'), ('can_delete_mysql_cluster', '\u5220\u9664\u8d44\u4ea7\u6743\u9650'), ('can_dumps_mysql_cluster', '\u5bfc\u51fa\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='NetDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicename', models.CharField(max_length=50, unique=True, verbose_name='\u8bbe\u5907\u540d')),
                ('in_band_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u5e26\u5185IP')),
                ('out_band_ip', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5e26\u5916IP')),
                ('in_net_ip', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4e92\u8054IP')),
                ('asset_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('asset_type', models.CharField(blank=True, choices=[(b'1', '\u8def\u7531\u5668'), (b'2', '\u4ea4\u6362\u673a'), (b'3', '\u9632\u706b\u5899'), (b'4', '\u52a0\u5bc6\u673a')], max_length=30, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('status', models.CharField(blank=True, choices=[(b'1', '\u4f7f\u7528\u4e2d'), (b'2', '\u672a\u4f7f\u7528'), (b'3', '\u6545\u969c'), (b'4', '\u5176\u5b83')], default='1', max_length=30, null=True, verbose_name='\u4f7f\u7528\u72b6\u6001')),
                ('brand', models.CharField(blank=True, choices=[(b'1', 'juniper'), (b'2', '\u534e\u4e09'), (b'3', '\u534e\u4e3a'), (b'4', '\u601d\u79d1'), (b'5', '\u535a\u79d1'), (b'6', '\u6df1\u4fe1\u670d'), (b'7', 'IBM'), (b'8', 'TP-LINK'), (b'9', '\u9510\u6377')], max_length=50, null=True, verbose_name='\u54c1\u724c')),
                ('brand_model', models.CharField(blank=True, max_length=150, null=True, verbose_name='\u578b\u53f7')),
                ('sn', models.CharField(blank=True, max_length=60, null=True, verbose_name='SN\u53f7 \u7801')),
                ('cabinet', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u673a\u67dc')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u673a\u67b6')),
                ('useuser', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7ba1\u7406\u5458')),
                ('purpose', models.CharField(blank=True, max_length=140, verbose_name='\u7528\u9014')),
                ('soft_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8f6f\u4ef6\u7248\u672c')),
                ('url', models.URLField(blank=True, max_length=100, verbose_name='\u8bbf\u95eeURL')),
                ('username', models.CharField(blank=True, max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='\u5bc6\u7801')),
                ('onlinedate', models.DateField(blank=True, default='2018-01-01', max_length=50, null=True, verbose_name='\u4e0a\u7ebf\u65f6\u95f4')),
                ('memo', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'NetDevices',
                'verbose_name': '\u7f51\u7edc\u8bbe\u5907',
                'verbose_name_plural': '\u7f51\u7edc\u8bbe\u5907',
            },
        ),
        migrations.CreateModel(
            name='NetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u7ec4\u540d')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.CreateModel(
            name='Oracle_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbtag', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6570\u636e\u5e93\u6807\u5fd7')),
                ('vist_ip', models.GenericIPAddressField(verbose_name='\u8bbf\u95eeVIP')),
                ('m_ip', models.GenericIPAddressField(verbose_name='\u7ba1\u7406IP')),
                ('other_ip', models.CharField(max_length=150, verbose_name='\u5176\u4ed6IP,\u9017\u53f7\u9694\u5f00')),
                ('port', models.IntegerField(default=1521, verbose_name='\u7aef\u53e3')),
                ('sid', models.CharField(blank=True, max_length=8, null=True, verbose_name='SID')),
                ('idc', models.CharField(blank=True, max_length=18, null=True, verbose_name='\u673a\u623f')),
                ('role', models.CharField(blank=True, choices=[('\u5355\u5e93', '\u5355\u5e93'), ('\u4e3b\u5e93', '\u4e3b\u5e93'), ('\u4ece\u5e93', '\u4ece\u5e93'), ('\u6c47\u603b', '\u6c47\u603b')], max_length=30, null=True, verbose_name='DB\u89d2\u8272')),
                ('db_status', models.CharField(blank=True, choices=[('\u4f7f\u7528\u4e2d', '\u4f7f\u7528\u4e2d'), ('\u672a\u4f7f\u7528', '\u672a\u4f7f\u7528'), ('\u6545\u969c', '\u6545\u969c'), ('\u5176\u5b83', '\u5176\u5b83')], max_length=30, null=True, verbose_name='DB\u72b6\u6001')),
                ('memory', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5206\u914d\u5185\u5b58')),
                ('disk', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u78c1\u76d8\u4f4d\u7f6e')),
                ('memo', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'Oracle_Instance',
                'verbose_name': 'Oracle\u96c6\u7fa4\u4e00\u4e2a\u5b9e\u4f8b',
                'verbose_name_plural': 'Oracle\u96c6\u7fa4\u4e00\u4e2a\u5b9e\u4f8b',
            },
        ),
        migrations.CreateModel(
            name='OracleCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u96c6\u7fa4\u540d')),
                ('arch', models.CharField(blank=True, choices=[('\u4e3b\u4ece', '\u4e3b\u4ece'), ('\u5355\u673a', '\u5355\u51fb'), ('rac', 'rac'), ('rac+\u4ece\u5e93', 'rac+\u4ece\u5e93')], max_length=30, null=True, verbose_name='\u96c6\u7fa4\u67b6\u6784')),
                ('db_version', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6570\u636e\u5e93\u7248\u672c')),
                ('defaultdb', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e3b\u7528DB')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
                ('operator', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='\u53ef\u89c1\u7684\u4eba')),
                ('tree_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.YewuTree', verbose_name='\u6240\u5c5e\u4ea7\u54c1\u7ebf')),
            ],
            options={
                'db_table': 'Oracle_Cluster',
                'verbose_name': 'Oracle \u96c6\u7fa4',
                'verbose_name_plural': 'Oracle\u96c6\u7fa4',
            },
        ),
        migrations.CreateModel(
            name='Oracletablespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablespace_name', models.CharField(max_length=50, verbose_name='\u8868\u7a7a\u95f4\u540d')),
                ('tablespace_size', models.CharField(max_length=50, verbose_name='\u5e93\u5927\u5c0f')),
                ('dbcluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.OracleCluster', verbose_name='\u6240\u5c5e\u96c6\u7fa4')),
            ],
            options={
                'db_table': 'Oracle_Tablespace',
                'verbose_name': 'Oracle \u8868\u7a7a\u95f4',
                'verbose_name_plural': 'Oracle\u8868\u7a7a\u95f4',
            },
        ),
        migrations.CreateModel(
            name='OracleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_user', models.CharField(blank=True, max_length=30, null=True)),
                ('db_password', models.CharField(blank=True, max_length=60, null=True)),
                ('privlige', models.CharField(blank=True, max_length=400, null=True, verbose_name='\u6743\u9650')),
                ('dbcluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.OracleCluster', verbose_name='\u6240\u5c5e\u96c6\u7fa4')),
            ],
            options={
                'db_table': 'Oracle_User',
                'verbose_name': 'Oracle\u7528\u6237',
                'verbose_name_plural': 'Oracle\u7528\u6237',
            },
        ),
        migrations.AddField(
            model_name='oracle_instance',
            name='CLUSTER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.OracleCluster', verbose_name='\u6240\u5c5e\u96c6\u7fa4'),
        ),
        migrations.AddField(
            model_name='netdevice',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.NetGroup', verbose_name='\u8bbe\u5907\u7ec4'),
        ),
        migrations.AddField(
            model_name='netdevice',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.Idc', verbose_name='\u6240\u5728\u673a\u623f'),
        ),
        migrations.AddField(
            model_name='mysql_user',
            name='dbcluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.MySQLCluster', verbose_name='\u6240\u5c5e\u96c6\u7fa4'),
        ),
        migrations.AddField(
            model_name='mysql_instance',
            name='dbcluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.MySQLCluster', verbose_name='\u6570\u636e\u5e93\u96c6\u7fa4'),
        ),
        migrations.AddField(
            model_name='mysql_db',
            name='dbcluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.MySQLCluster', verbose_name='\u6240\u5c5e\u96c6\u7fa4'),
        ),
    ]
