# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0006_auto_20180926_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql_db',
            name='dbcluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mysql_db', to='CMDB.MySQLCluster', verbose_name='\u6240\u5c5e\u96c6\u7fa4'),
        ),
        migrations.AlterField(
            model_name='mysql_instance',
            name='dbcluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mysql_instance', to='CMDB.MySQLCluster', verbose_name='\u6570\u636e\u5e93\u96c6\u7fa4'),
        ),
        migrations.AlterField(
            model_name='mysql_user',
            name='privlige',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u6743\u9650'),
        ),
    ]
