# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0006_auto_20180818_0847'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='idc',
            table='IDC',
        ),
    ]
