# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0007_auto_20180818_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='\u4e3b\u673a\u540d')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='\u8bbf\u95eeIP')),
                ('ip_public', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u516c\u7f51IP')),
                ('ip_control', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u8fdc\u7a0b\u7ba1\u7406\u5361IP')),
                ('ip_other', models.CharField(blank=True, max_length=850, null=True, verbose_name='\u5176\u4ed6IP')),
                ('asset_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('asset_type', models.CharField(blank=True, choices=[(b'1', '\u7269\u7406\u673a'), (b'2', '\u865a\u62df\u673a'), (b'4', '\u865a\u62df\u673a\u5bbf\u4e3b\u673a'), (b'3', '\u5b58\u50a8\u670d\u52a1\u5668'), (b'6', '\u52a0\u5bc6\u673a')], max_length=30, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('hostserver', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5bbf\u4e3b\u670d\u52a1\u5668')),
                ('status', models.CharField(blank=True, choices=[(b'1', '\u4f7f\u7528\u4e2d'), (b'2', '\u672a\u4f7f\u7528'), (b'3', '\u6545\u969c'), (b'4', '\u5176\u5b83')], max_length=30, null=True, verbose_name='\u4f7f\u7528\u72b6\u6001')),
                ('vendor', models.CharField(blank=True, choices=[(b'1', 'DELL'), (b'2', 'IBM'), (b'3', '\u534e\u4e3a'), (b'4', 'vmware'), (b'5', 'KVM'), (b'6', 'XEN')], max_length=250, null=True, verbose_name='\u54c1\u724c\u578b\u53f7')),
                ('cpu_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU\u578b\u53f7')),
                ('cpu_num', models.CharField(blank=True, max_length=3, null=True, verbose_name='CPU\u6838\u6570')),
                ('memory', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u786c\u76d8\u4fe1\u606f')),
                ('sn', models.CharField(blank=True, max_length=60, null=True, verbose_name='SN\u53f7 \u7801')),
                ('cabinet', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u673a\u67dc')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u673a\u67b6\u4f4d\u7f6e')),
                ('uplink_port', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u4e0a\u8054\u7aef\u53e3')),
                ('useuser', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u4f7f\u7528\u8005')),
                ('purpose', models.CharField(blank=True, max_length=40, verbose_name='\u7528\u9014')),
                ('system_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b')),
                ('port', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='ssh\u767b\u5f55\u7684\u7aef\u53e3')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='ssh\u767b\u5f55\u7684\u7528\u6237')),
                ('passwd', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='ssh\u767b\u5f55\u7684\u79d8\u5bc6')),
                ('sudo_passwd', models.CharField(blank=True, max_length=100, null=True)),
                ('keyfile', models.SmallIntegerField(blank=True, null=True)),
                ('ssh_status', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u7528\u6237\u8fde\u63a5\u72b6\u6001,0-\u4e0d\u53ef\u767b\u9646,1-\u5bc6\u7801\u767b\u9646,2-\u5bc6\u94a5\u767b\u9646')),
                ('onlinedate', models.DateField(default='2018-01-01', verbose_name='\u4e0a\u7ebf\u65f6\u95f4')),
                ('end_time', models.DateField(default='2019-01-01', verbose_name='\u5230\u4fdd\u65f6\u95f4')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('utime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('memo', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.Idc', verbose_name='\u6240\u5728\u673a\u623f')),
                ('tree_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.YewuTree', verbose_name='\u4e1a\u52a1\u6811ID')),
            ],
            options={
                'db_table': 'ALLHOSTS',
                'verbose_name': '\u4e3b\u673a\u8d44\u4ea7',
                'verbose_name_plural': '\u4e3b\u673a\u8d44\u4ea7',
            },
        ),
        migrations.CreateModel(
            name='Host_fail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP')),
                ('is_active', models.BooleanField(default=1, verbose_name='0-\u4e0d\u6d3b\u52a8ip,1-\u6d3b\u52a8ip')),
                ('is_ssh', models.BooleanField(default=1, verbose_name='0-\u65e0ssh\u7aef\u53e3,1-\u6709ssh\u7aef\u53e3')),
                ('port', models.CharField(blank=True, max_length=7, null=True, verbose_name='\u7aef\u53e3')),
                ('is_inhost', models.BooleanField(default=0, verbose_name='0-\u4e0d\u5728\u4e3b\u673a\u8868,1-\u5df2\u5728\u4e3b\u673a\u8868')),
            ],
            options={
                'db_table': 'host_loginfail',
                'verbose_name': '\u767b\u9646\u5931\u8d25\u4e3b\u673a',
                'verbose_name_plural': '\u767b\u9646\u5931\u8d25\u4e3b\u673a',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u7ec4\u540d')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
                ('serverList', models.ManyToManyField(blank=True, related_name='group_host', to='CMDB.Host', verbose_name='\u5305\u542b\u670d\u52a1\u5668')),
            ],
        ),
        migrations.CreateModel(
            name='IpSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, null=True, unique=True, verbose_name='I P \u5730\u5740')),
                ('subnet', models.CharField(blank=True, default='255.255.255.0', max_length=64, verbose_name='\u5b50\u7f51\u5730\u5740')),
                ('gateway', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7f51\u5173\u5730\u5740')),
                ('is_active', models.BooleanField(default=1, verbose_name='0-\u79bb\u7ebfip,1-\u5728\u7ebfip')),
                ('beizhu', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'IpSource',
                'verbose_name': '\u603bIP\u4fe1\u606f',
                'verbose_name_plural': '\u603bIP\u4fe1\u606f',
            },
        ),
    ]
