# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0008_auto_20180927_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql_instance',
            name='dbcluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CMDB.MySQLCluster'),
        ),
    ]
