# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0009_auto_20180928_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysql_instance',
            options={'verbose_name': 'mysql_Instance', 'verbose_name_plural': 'mysql_Instance'},
        ),
        migrations.AlterField(
            model_name='mysql_instance',
            name='idc',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='\u673a\u623f'),
        ),
    ]
