# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0010_auto_20180928_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysql_db',
            name='memo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
