# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0011_mysql_db_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysql_user',
            name='db_host',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
