# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0012_auto_20180904_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u80cc\u677f\u5e26\u5bbd')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='\u7ba1\u7406ip')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('passwd', models.CharField(blank=True, max_length=100, null=True)),
                ('sudo_passwd', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('port_number', models.SmallIntegerField(blank=True, null=True, verbose_name='\u7aef\u53e3\u4e2a\u6570')),
                ('firmware', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u56fa\u4ef6\u7248\u672c')),
                ('cpu', models.CharField(blank=True, max_length=100, null=True, verbose_name='cpu\u578b\u53f7')),
                ('stone', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('configure_detail', models.TextField(blank=True, max_length=100, null=True, verbose_name='\u914d\u7f6e\u8bf4\u660e')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMDB.Assets')),
            ],
            options={
                'db_table': 'opsmanage_network_assets',
                'verbose_name': '\u7f51\u7edc\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u7f51\u7edc\u8d44\u4ea7\u8868',
                'permissions': (('can_read_network_assets', '\u8bfb\u53d6\u7f51\u7edc\u8d44\u4ea7\u6743\u9650'), ('can_change_network_assets', '\u66f4\u6539\u7f51\u7edc\u8d44\u4ea7\u6743\u9650'), ('can_add_network_assets', '\u6dfb\u52a0\u7f51\u7edc\u8d44\u4ea7\u6743\u9650'), ('can_delete_network_assets', '\u5220\u9664\u7f51\u7edc\u8d44\u4ea7\u6743\u9650')),
            },
        ),
    ]
