# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0012_mysql_user_db_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='scan_conf_cmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syscmd', models.CharField(max_length=300, verbose_name='\u6267\u884c\u7684\u547d\u4ee4')),
            ],
            options={
                'db_table': 'scan_conf_cmd',
            },
        ),
        migrations.CreateModel(
            name='scan_conf_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nets', models.CharField(max_length=300, verbose_name='IP\u7f51\u6bb5,\u5982192.168.2')),
                ('nets_pass', models.CharField(max_length=100, verbose_name='\u672c\u5730\u5740\u5185\u4e0d\u53bb\u626b\u63cf\u7684\u5730\u5740\uff0c\u5982 1\uff0c2\uff0c4\uff0c\u9017\u53f7\u9694\u5f00')),
            ],
            options={
                'db_table': 'scan_conf_ip',
            },
        ),
        migrations.CreateModel(
            name='scan_conf_keyfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=300, verbose_name='keyfile ')),
            ],
            options={
                'db_table': 'scan_conf_keyfile',
            },
        ),
        migrations.CreateModel(
            name='scan_conf_port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=300, verbose_name='\u7aef\u53e3,\u59826666')),
            ],
            options={
                'db_table': 'scan_conf_port',
            },
        ),
        migrations.CreateModel(
            name='scan_conf_sshpass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_pass', models.CharField(max_length=300, verbose_name='ssh \u5bc6\u7801')),
            ],
            options={
                'db_table': 'scan_conf_sshpass',
            },
        ),
    ]
