# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0013_scan_conf_cmd_scan_conf_ip_scan_conf_keyfile_scan_conf_port_scan_conf_sshpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan_conf_ip',
            name='nets',
            field=models.CharField(max_length=30, unique=True, verbose_name='IP\u7f51\u6bb5,\u5982192.168.2'),
        ),
    ]
