# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0014_auto_20180905_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='YewuOracleCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('OracleNotOwner', models.ManyToManyField(related_name='OracleCluster', to='CMDB.OracleCluster')),
            ],
            options={
                'db_table': 'yewuoraclecall',
                'verbose_name': 'yewuoraclecall',
                'verbose_name_plural': 'yewuoraclecall',
            },
        ),
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u673a\u623f\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u63a5\u5165\u5e26\u5bbd'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='contact',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5ba2\u6237\u7ecf\u7406'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u79fb\u52a8\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='ip_range',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IP\u8303\u56f4'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='jigui',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u673a\u67dc\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='tel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u673a\u623f\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='yewutree',
            name='href',
            field=models.CharField(blank=True, help_text='moxingbiao', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='yewuoraclecall',
            name='chanpin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chanpin', to='CMDB.YewuTree'),
        ),
    ]
