# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0014_auto_20181010_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan_conf_ip',
            name='keys',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='keyfile'),
        ),
        migrations.AddField(
            model_name='scan_conf_ip',
            name='port',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u7aef\u53e3,\u59826666,22'),
        ),
        migrations.AddField(
            model_name='scan_conf_ip',
            name='ssh_pass',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ssh \u5bc6\u7801'),
        ),
    ]
