# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-10 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CMDB', '0015_auto_20180910_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oraclecluster',
            name='operator',
        ),
        migrations.AddField(
            model_name='oraclecluster',
            name='operator',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53ef\u89c1\u7684\u4eba'),
            preserve_default=False,
        ),
    ]
