# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0015_auto_20181016_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='scan_host_conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nets', models.CharField(max_length=30, unique=True, verbose_name='IP\u7f51\u6bb5,\u5982192.168.2')),
                ('nets_pass', models.CharField(max_length=100, verbose_name='\u672c\u5730\u5740\u5185\u4e0d\u53bb\u626b\u63cf\u7684\u5730\u5740\uff0c\u5982 1\uff0c2\uff0c4\uff0c\u9017\u53f7\u9694\u5f00')),
                ('port', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u7aef\u53e3,\u59826666,22')),
                ('ssh_pass', models.CharField(blank=True, max_length=300, null=True, verbose_name='ssh \u5bc6\u7801')),
                ('keys', models.CharField(blank=True, max_length=300, null=True, verbose_name='keyfile')),
            ],
            options={
                'db_table': 'scan_host_conf',
            },
        ),
    ]
