# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0016_scan_host_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan_host_conf',
            name='beizhu',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='beizhu'),
        ),
        migrations.AlterField(
            model_name='scan_host_conf',
            name='nets_pass',
            field=models.CharField(max_length=200, verbose_name='\u672c\u5730\u5740\u5185\u4e0d\u53bb\u626b\u63cf\u7684\u5730\u5740\uff0c\u5982 1\uff0c2\uff0c4\uff0c\u9017\u53f7\u9694\u5f00'),
        ),
    ]
