# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0017_auto_20181016_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlcluster',
            name='plat_user',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5e73\u53f0\u64cd\u4f5c\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='mysqlcluster',
            name='plat_user_pass',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='\u5e73\u53f0\u64cd\u4f5c\u7528\u6237\u5bc6\u7801'),
        ),
    ]
