# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0018_auto_20181025_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysql_db',
            name='db_rows',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='\u5e93\u5927\u5c0f(Mb)'),
        ),
        migrations.AddField(
            model_name='mysql_db',
            name='index_size',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='\u7d22\u5f15\u5927\u5c0fMb'),
        ),
        migrations.AlterField(
            model_name='mysql_db',
            name='db_size',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='\u5e93\u5927\u5c0f(Mb)'),
        ),
    ]
