# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0020_auto_20181029_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql_user',
            name='dbcluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mysql_user', to='CMDB.MySQLCluster', verbose_name='\u6240\u5c5e\u96c6\u7fa4'),
        ),
    ]
