# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0023_auto_20181029_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('\u7269\u7406\u673a', '\u7269\u7406\u673a'), ('\u865a\u62df\u673a', '\u865a\u62df\u673a'), ('\u5b58\u50a8\u670d\u52a1\u5668', '\u5b58\u50a8\u670d\u52a1\u5668'), ('\u865a\u62df\u673a\u5bbf\u4e3b\u673a', '\u865a\u62df\u673a\u5bbf\u4e3b\u673a'), ('\u5b58\u50a8\u670d\u52a1\u5668', '\u5b58\u50a8\u670d\u52a1\u5668'), ('\u52a0\u5bc6\u673a', '\u52a0\u5bc6\u673a')], max_length=30, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vendor',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u54c1\u724c\u578b\u53f7'),
        ),
    ]
