# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0024_auto_20181031_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yewutree',
            options={'verbose_name': '\u4e1a\u52a1\u6811', 'verbose_name_plural': '\u4e1a\u52a1\u6811'},
        ),
        migrations.AlterField(
            model_name='host',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('\u865a\u62df\u673a', '\u865a\u62df\u673a'), ('\u7269\u7406\u673a', '\u7269\u7406\u673a'), ('\u865a\u62df\u673a\u5bbf\u4e3b\u673a', '\u865a\u62df\u673a\u5bbf\u4e3b\u673a'), ('\u5b58\u50a8\u670d\u52a1\u5668', '\u5b58\u50a8\u670d\u52a1\u5668')], max_length=30, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='yewutree',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='CMDB.YewuTree', verbose_name='\u7236\u8282\u70b9'),
        ),
        migrations.AlterModelTable(
            name='yewutree',
            table='yewuTree',
        ),
    ]
