# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0025_auto_20181112_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='YewuTreeMptt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('href', models.CharField(blank=True, help_text='moxingbiao', max_length=200, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='CMDB.YewuTreeMptt', verbose_name='\u7236\u8282\u70b9')),
            ],
            options={
                'db_table': 'yewuTreeMptt',
                'verbose_name': '\u4e1a\u52a1\u6811',
                'verbose_name_plural': '\u4e1a\u52a1\u6811',
            },
        ),
        migrations.RemoveField(
            model_name='yewutree',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='yewutree',
            name='root',
        ),
        migrations.AlterField(
            model_name='host',
            name='tree_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.YewuTreeMptt', verbose_name='\u4e1a\u52a1\u6811ID'),
        ),
        migrations.AlterField(
            model_name='mysqlcluster',
            name='tree_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.YewuTreeMptt', verbose_name='\u6240\u5c5e\u4ea7\u54c1\u7ebf'),
        ),
        migrations.AlterField(
            model_name='oraclecluster',
            name='tree_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.YewuTreeMptt', verbose_name='\u6240\u5c5e\u4ea7\u54c1\u7ebf'),
        ),
        migrations.AlterField(
            model_name='yewuoraclecall',
            name='chanpin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chanpin', to='CMDB.YewuTreeMptt'),
        ),
        migrations.DeleteModel(
            name='YewuTree',
        ),
    ]
