# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0027_yewutreemptt_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='yewutreemptt',
            name='isLast',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u6700\u540e\u8282\u70b9'),
        ),
    ]
