# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0032_auto_20181120_1532'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cron_config',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='cron_config',
            name='cron_server',
        ),
        migrations.AlterUniqueTogether(
            name='disk_assets',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='disk_assets',
            name='assets',
        ),
        migrations.DeleteModel(
            name='Log_Assets',
        ),
        migrations.DeleteModel(
            name='Log_Cron_Config',
        ),
        migrations.RemoveField(
            model_name='network_assets',
            name='assets',
        ),
        migrations.AlterUniqueTogether(
            name='networkcard_assets',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='networkcard_assets',
            name='assets',
        ),
        migrations.DeleteModel(
            name='Raid_Assets',
        ),
        migrations.AlterUniqueTogether(
            name='ram_assets',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ram_assets',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='server_assets',
            name='assets',
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.DeleteModel(
            name='Cron_Config',
        ),
        migrations.DeleteModel(
            name='Disk_Assets',
        ),
        migrations.DeleteModel(
            name='Network_Assets',
        ),
        migrations.DeleteModel(
            name='NetworkCard_Assets',
        ),
        migrations.DeleteModel(
            name='Ram_Assets',
        ),
        migrations.DeleteModel(
            name='Server_Assets',
        ),
    ]
