# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0033_auto_20181204_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Line_Assets',
        ),
        migrations.DeleteModel(
            name='Zone_Assets',
        ),
    ]
