# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0034_auto_20181204_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idc', to='CMDB.Idc', verbose_name='\u6240\u5728\u673a\u623f'),
        ),
    ]
