# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0035_auto_20181210_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkCard_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
                ('macaddress', models.CharField(blank=True, max_length=64, null=True, verbose_name='MAC')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('module', models.CharField(blank=True, max_length=50, null=True)),
                ('mtu', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5728\u7ebf')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB.Host')),
            ],
            options={
                'db_table': 'networkcard_assets',
                'verbose_name': '\u670d\u52a1\u5668\u7f51\u5361\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u670d\u52a1\u5668\u7f51\u5361\u8d44\u4ea7\u8868',
            },
        ),
        migrations.AlterUniqueTogether(
            name='networkcard_assets',
            unique_together=set([('host', 'macaddress')]),
        ),
    ]
