# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-21 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0038_auto_20181221_1339'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='host',
            index_together=set([('ip', 'hostname')]),
        ),
    ]
