# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-21 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0040_auto_20181221_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='CMDB.Idc', verbose_name='\u6240\u5728\u673a\u623f'),
        ),
    ]
