# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-24 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0041_auto_20181221_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql_user',
            name='privlige',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='\u6743\u9650'),
        ),
    ]
