# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-24 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0042_auto_20181224_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlcluster',
            name='down_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e0b\u7ebf\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='mysqlcluster',
            name='up_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e0a\u7ebf\u65e5\u671f'),
        ),
    ]
