# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_auto_20180905_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u4f5c\u8005\u540d')),
                ('book', models.ManyToManyField(help_text='\u4e66\u7c4d\u548c\u4f5c\u8005\u591a\u5bf9\u591a\u7684\u5173\u7cfb', related_name='books', related_query_name='authors', to='test.Book')),
            ],
        ),
    ]
